# Python

This notebook contains relevant information about Python that will be helpful during the whole class.

## Jupyter is a Python shell divided in cells


This cell is a *Markdown* cell (for texts like notes, manuals, etc.)
You can edit this cell with a double click. `Ctrl + Enter` executes the cell, i.e. annotations for headlines, bullet lists and the like will be evaluated and the formatted result will be shown.

The cell following the **"Hello World!"** headline is a *Code* cell
It consists of an input `In [ ]` and an output.
The execution of the entered code is started with `Ctrl + Enter`, just like the Markdown cell type.

If the square brackets of the input cell are empty, the cell has not been executed yet.
A star (`In [*]`) shows that the code of the cell is currently running.
After the computation finished, the star is replaced with a number (e.g. `In [5]`) and the output (if any is produced) appears directly below the cell.

The cells can be executed multiple times and in any order. The actual program flow is thus not defined by the cell order but by the numbers in the square brackets.

# Basics

As usual, first thing we need is a hello world!

### Hello world!

In [ ]:
print("hello world!")

hello world!


What can we see from this first Python code line?

- `print` is a key word in Python
- strings can be defined just by using quotes
- we don't need to create any main or any class to run code in Python

### Here is a list of Python key words

|   |   |   |   |   |
|:---|:---|:---|:---|:---|
|`and`|`as`|`assert`|`break`
|`class`|`continue`|`def`|`del`  
|`elif`|`else`|`except`|`exec`
|`finally`|`for`|`from`|`global`
|`if`|`import`|`in`|` is`
|`lambda`|`not`|`or`|` pass`
|`print`|`raise`|`return`|`try`
|`while`|`with`|`yield`

Taken from [Lean Python](http://file.allitebooks.com/20161117/Lean%20Python.pdf)

### Defining variables:

In python you do not need to declare the type of the variable. The interpreter will infer them dynamically.
In Python you can find the type out using `type()`. Defining variables is just as easy as using `=`. All variables have a type analogue to Java or any other programming language.

In [ ]:
a = 4   # I'm an integer
b = 5.2 # I'm a float

In [ ]:
variable = "I'm a variable" # This is a string

c, d, e = 1, 2, 3 # this is the same as saying c = 1, d =  2, e = 3

print(e)

3


#### TASK1: type of variables

In [ ]:
# Now it's your turn to find out, what is the type of variable, a and b
type_a = None
type_b = None
## YOUR_CODE_STARTS_HERE
type_a, type_b = type(a), type(b)
## YOUR_CODE_ENDS_HERE
## RESULT_CHECKING_POINT (result should be <class 'int'> <class 'float'>)
print(type_a, type_b)

<class 'int'> <class 'float'>


What about math opperations, what type should come out of summing __a__ and __b__

In [ ]:
# let's try it out!

print(a + b) # Mixing integer and float numbers results in float type

9.2


#### TASK2: What about substraction and so on?

In [ ]:
# It's your turn to compute these :)
sub_a_b = None
mul_a_b = None
div_a_b = None
mod_d_e = None

# substraction
## YOUR_CODE_STARTS_HERE
sub_a_b = a - b
mul_a_b = a * b
div_a_b = a / b
mod_d_e = d % e
## YOUR_CODE_ENDS_HERE
## RESULT_CHECKING_POINT (result should be -1.2000000000000002 20.8 0.7692307692307692 2)
print(sub_a_b, mul_a_b, div_a_b, mod_d_e)

-1.2000000000000002 20.8 0.7692307692307692 2


__Question__: What is the resulting type of a multiplication and what is the resulting type of a division? Are the results always of the same type?

### Blocks

In Python each statement is defined in a line. Sometimes, you can use a semicolon (;) to define several statement in a line.

Other programming languages have { ... } to define a block, in Python we have **identation** and colon (:) in order to open the block.


In [ ]:
# if-statement - what will be the output?

x = 5

if x < 5:
    print('x is smaller than 5')
elif x == 5:
    print('x is equal to 5')
else:
    print('x is greater than 5')
print('end of the if')

x is equal to 5
end of the if


In [ ]:
# What can you say about this loop?

# count = 0
# while count < 5: # Here begins my block
#     print(count)
# count += 1

__Question__: What do we have to change for counting up to 5?<br>

#### TASK3: sum up all numbers from 1 to 100

In [ ]:
sum_1_to_100 = None
## YOUR_CODE_STARTS_HERE
sum_1_to_100 = 0
n = 1
while n < 100 + 1:
    sum_1_to_100 += n
    n += 1

# OR:

sum_1_to_100 = 0
for n in range(1, 100+1):
  sum_1_to_100 += n
## YOUR_CODE_ENDS_HERE
## RESULT_CHECKING_POINT (result should be 5050)
print(sum_1_to_100)

5050


#### TASK4: sum up all numbers from 1 to 100 that are divisible by 3

In [ ]:
result = None
## YOUR_CODE_STARTS_HERE
result = 0
for n in range(1, 100+1):
  if n % 3 == 0:
    result += n
## YOUR_CODE_ENDS_HERE
## RESULT_CHECKING_POINT (result should be 1683)
print(result)

1683


### Strings

Let's focus on strings because this class will be mainly on how we handle strings and many fun things that we can make with text. Again as we saw in our *hello world* example, we need quote to create a string, whether single (') or double (") quotes it's actually not important, but **don't mix them**. Strings are a sequence of characters that concatenated form a text. We can also have one character strings or an empty string.

In [ ]:
first_str = "Hello"
second_str = "world"
empty_str = ""
one_ch_str = "!"

#### String operations

In [ ]:
# Concatenation

print(first_str +  second_str + one_ch_str)

Helloworld!


What's missing?

In [ ]:
space_str = " "
print(first_str + space_str + second_str + one_ch_str)

Hello world!


In [ ]:
# Repetition of strings

print(first_str + space_str + second_str + (one_ch_str * 5))

Hello world!!!!!


In [ ]:
greeting = first_str + space_str
print(greeting)

Hello 


__Important__: We can also use ordinary "arithmetic" operations on strings. So keep in mind, that the operators are overloaded.

In [ ]:
greeting += second_str
print(greeting)

Hello world


__Question__: What is the problem with following instruction?

*In Python, exceptions are errors that occur during the execution of a program. Instead of causing the program to crash, exceptions can be caught and handled so that the program can continue running.*

In [ ]:
n = 5
try:
  print('The value of n is ' + n)
except Exception as e:
  print(e)

can only concatenate str (not "int") to str


#### TASK5: The value of n is 5

Fix the issue above and print the string "The value of n is 5" using str concatentation operation

In [ ]:
## YOUR_CODE_STARTS_HERE
print('The value of n is ' + str(n))
## YOUR_CODE_ENDS_HERE
## RESULT_CHECKING_POINT (result should be "The value of n is 5")

The value of n is 5


We can index elements using [ ] as follows

In [ ]:
print(first_str[3])

l


In [ ]:
long_str = "pneumonoultramicroscopicsilicovolcanoconiosis"

# Index ranges

print(long_str[:6]) #== long_str[0:6]

pneumo


__Question__: How many characters does long_str[:6] contain? What can we implicate for the last index?

Indexes begin with 0 and end with length -1. __Attention__: The last position (index) of a string is long_str[-1] == long_str[len(long_str) - 1], but in a range the last index is exclusive.

In [ ]:
print(len(long_str))

45


In [ ]:
print(long_str[30:-1])

volcanoconiosi


__Question__: We saw above the equivalence of long_str[:6] == long_str[0:6]. What is the equivalent expression to the following instruction?

In [ ]:
print(long_str[30:])

volcanoconiosis


An overview of logical operators:

- == equal
- != unequal
- < less than
- \> greater than
- <= less than or equal to >= greater than or equal to

### Important!
- == means comparison
- = means assignment

In [ ]:
print(first_str[2] == first_str[3])
print(first_str[1] == first_str[3])

True
False


#### TASK 6: how many o's do we have in `long_str`

In [ ]:
## YOUR_CODE_STARTS_HERE
print(len([ch for ch in long_str if ch == "o"]))
## YOUR_CODE_ENDS_HERE
## RESULT_CHECKING_POINT (result should be 9)

9


#### String Methods

There are several methods provided to support transforming, validating and in general working with strings. Here we have some of them.

In [ ]:
text = 'This is text'
nums = '123456'

#### `str.find`

In [ ]:
find1 = text.find('is')
find2 = text.find('your')

__Question__: What is the output of the find-method?

__Task__: We want to get a user-friendly output if the words 'is' or 'your' can be found in the variable `text`, i.e.<br>
'is' found in 'This is text'<br>
'your' found in 'This is text'<br>
if both words could be found in the text or the negated form if the word wasn't found. Try to be most generic as possible, i.e. hard code as few as possible.

In [ ]:
SUBSTRING_NOT_EXISTS = None

## YOUR_CODE_STARTS_HERE
# Assign the value to `SUBSTRING_NOT_EXISTS`
SUBSTRING_NOT_EXISTS = -1
## YOUR_CODE_ENDS_HERE

## RESULT_CHECKING_POINT (result should be "is does exist" "your does not exist")
for substr in ['is', 'your']:
    if text.find(substr) == SUBSTRING_NOT_EXISTS:
        print(substr + " does not exist")
    else:
        print(substr + " does exist")

is does exist
your does not exist


####  Validation checks `str.isxxx`

In [ ]:
text.isalpha()
text.isdigit()
nums.isdigit()

True

#### Concatenation: `str.join`

In [ ]:
print(''.join((text,nums)))
print(' '.join((text,nums)))

This is text123456
This is text 123456


#### Format important!!!

In [ ]:
fname = "John"
lname = "Doe"
age = "24"
print("{first} {last} is {age} years old".format(first=fname, last=lname, age=age))
print(f"{fname} {lname} is {age} years old")
print("%s %s is %s years old" % (fname, lname, age))  # old c-like way

John Doe is 24 years old
John Doe is 24 years old
John Doe is 24 years old


#### Case changing `str.upper` and `str.lower`. Important!!!

In [ ]:
text.upper()
text.lower()

'this is text'

#### `str.split`

In [ ]:
text.split(' ')

['This', 'is', 'text']

#### Substitution

In [ ]:
text.replace('is','was')

'Thwas was text'

#### Stripping

In [ ]:
text_with_space = " a sentence with extra space    "
text_with_space.rstrip(), text_with_space.lstrip(), text_with_space.strip()

(' a sentence with extra space',
 'a sentence with extra space    ',
 'a sentence with extra space')

#### TASK 7: strip noise

In [ ]:
# be careful with the cases when there is an argument:
text_with_noise = "a sentence..^%&^%&^"
strip_argument = None

## YOUR_CODE_STARTS_HERE
# assign your values to `strip_argument`. Be as concise as possible
strip_argument = "^&.%"
## YOUR_CODE_ENDS_HERE

## RESULT_CHECKING_POINT  (result should be "a sentence")
print(text_with_noise.strip(strip_argument))

a sentence


# Functions and Data Structures
Some tasks are based on tasks on https://www.practicepython.org/.<br>
For better readability and encapsulation of our code, we can define **function**s, that perform specific instructions. We can call functions with inputs and functions may return an output, but don't have to. A function can be defined with the keyword *def* followed by the name of the function.

In [ ]:
# Function without input and without output
def hello_world():
    print('Hello World!')

# Function with input, but without output
def print_my_input(my_input):
    print(my_input)

# Function with input and output
def add(value1, value2):
    return value1 + value2

Defined functions can be called by typing the function name:

In [ ]:
hello_world()
print_my_input('Hello World!')
print(add(1, 3))

Hello World!
Hello World!
4


## `list`

Lists in Python are like magic they may contain all kinds of objects together e.g. float, integers, strings even lists inside lists as we had in our previous exercise submission.


#### Task 7: iterate over list
Iterate over the list and store its element less than 15 into `new_list`

In [ ]:
list_of_numbers = [3, 7, 10, 23, 8, 15, 34, 12, 16, 5, 45, 63, 13, 9]
new_list = None
## YOUR_CODE_STARTS_HERE
new_list = [n for n in list_of_numbers if n < 15]
## YOUR_CODE_ENDS_HERE
## RESULT_CHECKING_POINT  (result should be [3, 7, 10, 8, 12, 5, 13, 9])
print(new_list)

[3, 7, 10, 8, 12, 5, 13, 9]


#### Task 8: write function `list_intersection`

Given two input lists, write a function to output the intersection without duplicates.

> Hint: use `in` in the condition, e.g. `1 in [1,2]` and `1 not in [1,2]`

In [ ]:
list1 = [1,3,5,6,3]
list2 = [1,2,3]

def list_intersection(list1, list2):
  intersection = []
  ## YOUR_CODE_STARTS_HERE
  for n in list1:
    if n in list2 and n not in intersection:
      intersection.append(n)
  ## YOUR_CODE_ENDS_HERE
  return intersection
## RESULT_CHECKING_POINT  (result should be [1, 3])
print(list_intersection(list1, list2))

[1, 3]


### `list.append` and `list.extend`

In [ ]:
list1 = [1,3,5,6,3]
list1.append(7)
list1.extend(list2)
print(list1)

[1, 3, 5, 6, 3, 7, 1, 2, 3]


### `list1 + list2`

In [ ]:
list1 = [1,3,5,6,3]
list2 = [1,2,3]
print(list1 + list2)

[1, 3, 5, 6, 3, 1, 2, 3]


### `list.pop`

In [ ]:
list1 = [1,3,5,6,3]
print(list1.pop(4), list1)

3 [1, 3, 5, 6]


## `dict`

You can also create dictionaries (Map/HashMap in Java).
Using this structure you can link elements. We call them keys and values.



### Keys must be unique

Otherwise you will overwrite the value of that key

In [ ]:
dictionary = {}
dictionary["a"] = 1
dictionary["b"] = 2
dictionary["c"] = 3
print(dictionary)

dictionary["a"] = [1, 2, 3, 5]
print(dictionary)

{'a': 1, 'b': 2, 'c': 3}
{'a': [1, 2, 3, 5], 'b': 2, 'c': 3}


### `dict.setdefault`

In [ ]:
id2str = {}
print(id2str.setdefault(1, "one"))
print(id2str[1])

one
one


### `dict.get`

In [ ]:
id2str = {}
print(id2str.get(1, None))
print(id2str)        

None
{}


### TASK 9: vocab construction. Important!!!

You are required to implement a `build_vocab` function that takes in a list of documents (strings) and outputs a vocabulary dictionary. This dictionary should map each unique word to a corresponding unique ID (integer). The IDs should start from 0 and increment sequentially in the order that words first appear across the documents. All the words should be converted to their lowercase first.

In [ ]:
doc1 = "The first document."
doc2 = "And this is the second document."

def build_vocab(docs):
  vocab = {}  # a mapping from words to the corresponding IDs (integers)
  ## YOUR_CODE_STARTS_HERE
  for doc in docs:
    for word in doc.lower().split():
      vocab.setdefault(word, len(vocab))
  ## YOUR_CODE_ENDS_HERE
  return vocab

## RESULT_CHECKING_POINT (result should be {'the': 0, 'first': 1, 'document.': 2, 'and': 3, 'this': 4, 'is': 5, 'the': 6, 'second': 7})
build_vocab([doc1, doc2])

{'the': 0,
 'first': 1,
 'document.': 2,
 'and': 3,
 'this': 4,
 'is': 5,
 'second': 6}

# Read from/Write to Disk

## Text files

In [ ]:
# Open the file in write mode ('w'), which overwrites the file if it already exists
with open('example.txt', 'w') as file:
    file.write("Hello, World!\nThis is a new line of text.")

# Open the file in read mode ('r')
with open('example.txt', 'r') as file:
    content = file.read()  # Read the entire content of the file
    print(content)

Hello, World!
This is a new line of text.


## Pickle for Serializing/Deserializing Python Objects

In [ ]:
import pickle

# Define a sample Python object (like a dictionary)
data = {"name": "Alice", "age": 30, "job": "Scientist"}

# Open the file in write-binary mode ('wb')
with open('data.pkl', 'wb') as file:
    pickle.dump(data, file)  # Dump the Python object into the file

In [ ]:
# Open the file in read-binary mode ('rb')
with open('data.pkl', 'rb') as file:
    loaded_data = pickle.load(file)  # Load the object from the file
    print(loaded_data)

{'name': 'Alice', 'age': 30, 'job': 'Scientist'}


## JSON

In [ ]:
import json

# Define a Python object (e.g., dictionary)
data = {"name": "Alice", "age": 30, "job": "Scientist"}

# Open the file in write mode ('w')
with open('data.json', 'w') as file:
    json.dump(data, file, indent=4)  # Use indent=4 for pretty-printing

In [ ]:
# Open the file in read mode ('r')
with open('data.json', 'r') as file:
    loaded_data = json.load(file)  # Load the JSON data as a Python object
    print(loaded_data)

{'name': 'Alice', 'age': 30, 'job': 'Scientist'}


##  Pandas (for CSV Files)

Pandas is a software library written for the Python programming language for data manipulation and analysis. It supports reading/writing operations for files of many different formats, e.g. .csv/.tsv, .xlsx, .jsonl (json lines), etc.

In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'Job': ['Engineer', 'Doctor', 'Teacher']}
df = pd.DataFrame(data)

# Write the DataFrame to a CSV file
df.to_csv('output.csv', index=False)  # index=False prevents adding an extra index column

In [ ]:
# Read the CSV file into a DataFrame
df = pd.read_csv('output.csv')

# Display the first few rows of the DataFrame
print(df.head())

      Name  Age       Job
0    Alice   25  Engineer
1      Bob   30    Doctor
2  Charlie   35   Teacher


It also supports a lot of convenient operations for data preprocessing and analysis. For example: (learn more [here](https://pandas.pydata.org/docs/user_guide/10min.html))

In [ ]:
df[df["Age"] >= 20]

Name  Age       Job
0    Alice   25  Engineer
1      Bob   30    Doctor
2  Charlie   35   Teacher

# Numpy library and `import`
Numpy is a python library for mathematical purposes and with good support for vectors and matrices. A library can be loaded into your file using the *import* instruction. We can define an abbreviation for used libraries, so that we do not need to type the full name.

In [ ]:
import numpy as np

a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
a = a.reshape(5,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


#### TASK10: defining numpy array

Define the numpy arrays (using `np.array`) which contains 10 Zeros, 10 Ones and 10 Fives. (Note: There are more than one solutions)

In [ ]:
np_array = None

## YOUR_CODE_STARTS_HERE
np_array = np.array([0] * 10 + [1] * 10 + [5] * 5)
## YOUR_CODE_ENDS_HERE
## RESULT_CHECKING_POINT  (result should be [1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 6 6 6 6 6])
print(np_array + 1)  # benefit: such matrix-related operations will be extremely fast and convenient

[1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 6 6 6 6 6]


### `np.ndarray.shape`, `np.ndarray.ndim`, `np.ndarray.dtype`

__Question__: What is actually the difference between them? Discuss this with your neighbor.

In [ ]:
print("shape of a is:", a.shape)
print("dimensions in a:", a.ndim)
print("type of a is:", a.dtype)

shape of a is: (5, 3)
dimensions in a: 2
type of a is: int64


### Numpy math operations

We can also use the ordinary mathematical operations on vectors, i.e. Numpy-arrays.

In [ ]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
print("shapes:", a.shape, b.shape)
print(a)
print(b)
print(a + b)
print(a - b)
print(a.sum())
print(a ** 2)
print(a > b * 10)
a[[0, 3]] += 1
print(a)

shapes: (4,) (4,)
[10 20 30 40]
[0 1 2 3]
[10 21 32 43]
[10 19 28 37]
100
[ 100  400  900 1600]
[ True  True  True  True]
[11 20 30 41]


__Question__: What is the difference between the following instructions? Discuss this with your neighbor.

In [ ]:
print(a * 2)
print(a * b)
print(a.dot(b))

[22 40 60 82]
[  0  20  60 123]
203


### More ways to create `np.ndarray`

In [ ]:
np.zeros(4), np.ones(4), np.full((3, 4), 2)

(array([0., 0., 0., 0.]),
 array([1., 1., 1., 1.]),
 array([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]]))

### TASK 11: `Wx + b`

Given the matrix/vector W, x and b, compute `Wx+b`.
> Hint: `np.matmul`

In [ ]:
W = np.array([[1,2,3], [4,5,6], [7,8,9]])
x = np.ones(3)
b = np.ones(3)
new_x = None

## YOUR_CODE_STARTS_HERE
new_x = np.matmul(W, x) + b
## YOUR_CODE_ENDS_HERE
## RESULT_CHECKING_POINT  (result should be [ 7. 16. 25.])
print(new_x)

[ 7. 16. 25.]


### Broadcasting

In [ ]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.ones((1, 3))
print(A * B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Objective-Oriented Programming


## Defining a class

In [ ]:
class BankAccount:
    def __init__(self, account_holder, balance=0.0):
        # Initialize the account with the account holder's name and balance
        self.account_holder = account_holder
        self.balance = balance

    def deposit(self, amount):
        # Method to deposit money
        if amount > 0:
            self.balance += amount
            print(f"Deposited {amount} to {self.account_holder}'s account.")
        else:
            print("Deposit amount must be positive.")

    def withdraw(self, amount):
        raise NotImplementedError("Withdraw method not implemented.")

    def get_balance(self):
        # Return the current balance
        return self.balance

# Example usage
account = BankAccount("Alice")
account.deposit(100)
print(f"Balance: {account.get_balance()}")

Deposited 100 to Alice's account.
Balance: 100.0


## TASK12: implemet `BankAccount.withdraw`

In [ ]:
def withdraw(self, amount):
    # Method to withdraw money
    ## YOUR_CODE_STARTS_HERE
    if amount > 0 and self.balance >= amount:
        self.balance -= amount
    ## YOUR_CODE_ENDS_HERE

## RESULT_CHECKING_POINT
BankAccount.withdraw = withdraw
account.withdraw(30)
print(f"Balance: {account.get_balance()}")

Balance: 70.0


## Static Method, Class Method, and Property

In [ ]:
class BankAccount:
    interest_rate = 0.02  # Class-level attribute (shared across instances)

    def __init__(self, account_holder, balance=0.0):
        self.account_holder = account_holder
        self._balance = balance

    def deposit(self, amount):
        if amount > 0:
            self._balance += amount
        else:
            print("Deposit amount must be positive.")

    def withdraw(self, amount):
        if amount > 0 and self._balance >= amount:
            self._balance -= amount
        else:
            print("Insufficient balance or invalid amount.")

    @staticmethod
    def bank_policy():
        # Static method to display the bank's general policy (no instance or class data needed)
        return "Bank follows standard regulations."

    @classmethod
    def from_string(cls, account_info_str):
        # Class method to create an account from a string representation
        raise NotImplementedError("from_string method not implemented.")

    @property
    def balance(self):
        # Property to get the balance (read-only)
        return self._balance

# Example usage
account = BankAccount("Bob", 200)
print(f"Initial balance: {account.balance}")
account.deposit(50)
print(f"Balance after deposit: {account.balance}")

# Access static method
print(BankAccount.bank_policy())

# Change interest rate using class method
print(f"New interest rate: {BankAccount.interest_rate}")

Initial balance: 200
Balance after deposit: 250
Bank follows standard regulations.
New interest rate: 0.02


## TASK13: `from_string`

In [ ]:
@classmethod
def from_string(cls, account_info_str):
    # Class method to create an account from a string representation
    ## YOUR_CODE_STARTS_HERE
    account_holder, balance = account_info_str.split(',')
    return cls(account_holder, balance)
    ## YOUR_CODE_ENDS_HERE

# RESULT_CHECKING_POINT  (result should be "Holder: Charlie, balance: 350")
BankAccount.from_string = from_string
bank_account = BankAccount.from_string("Charlie,350")
print(f"Holder: {bank_account.account_holder}, balance: {bank_account.balance}")

Holder: Charlie, balance: 350


## Abstract Class

One can inherit a class directly: `class Parent: ...` -> `class Child(Parent)` in Python. But it provides a more explicit way to do this: via Abstract Base Class (`abc.ABC`).

In [ ]:
from abc import ABC, abstractmethod

class Account(ABC):
    @abstractmethod
    def deposit(self, amount):
        pass  # Abstract method to be implemented by subclasses

    @abstractmethod
    def withdraw(self, amount):
        pass  # Abstract method to be implemented by subclasses

    @abstractmethod
    def get_balance(self):
        pass  # Abstract method to be implemented by subclasses

class BankAccount(Account):
    def __init__(self, account_holder, balance=0.0):
        self.account_holder = account_holder
        self.balance = balance

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            print(f"Deposited {amount} to {self.account_holder}'s account.")
        else:
            print("Deposit amount must be positive.")

    def withdraw(self, amount):
        if amount > 0 and self.balance >= amount:
            self.balance -= amount
            print(f"Withdrew {amount} from {self.account_holder}'s account.")
        else:
            print("Insufficient balance or invalid amount.")

    def get_balance(self):
        return self.balance

# Example usage
account = BankAccount("Charlie", 500)
account.deposit(100)
account.withdraw(200)
print(f"Balance: {account.get_balance()}")

Deposited 100 to Charlie's account.
Withdrew 200 from Charlie's account.
Balance: 400


One direct benefit of using ABC is that it will raise an exception if one did not inherit the base class properly:

In [ ]:
class BakeryAccount(Account):
  pass

try:
  BakeryAccount()
except Exception as e:
  print(type(e), e)

<class 'TypeError'> Can't instantiate abstract class BakeryAccount with abstract methods deposit, get_balance, withdraw


# Decorators and `dataclass`

A decorator is a function that takes another function or a class and extends its behavior without explicitly modifying it. This is useful when you want to add some reusable logic before or after a function’s main execution.


In [ ]:
def decorator_function(original_function):
    def wrapper_function(*args, **kwargs):
        print("Before executing the function")
        result = original_function(*args, **kwargs)
        print("After executing the function")
        return result
    return wrapper_function

@decorator_function
def display_message():
    print("Hello, World!")

display_message()

Before executing the function
Hello, World!
After executing the function


Decorator for a class:

In [ ]:
def class_logger(cls):
    class WrappedClass(cls):
        def __init__(self, *args, **kwargs):
            print(f"Creating an instance of {cls.__name__}")
            super().__init__(*args, **kwargs)

    return WrappedClass

@class_logger
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def greet(self):
        return f"Hello, my name is {self.name} and I am {self.age} years old."

# Creating an instance of the class
person = Person("Alice", 30)
print(person.greet())

Creating an instance of Person
Hello, my name is Alice and I am 30 years old.


Introduced in Python 3.7, the dataclass module is a decorator that automatically generates special methods for classes, such as __init__(), __repr__(), __eq__(), and more. It’s a great way to reduce boilerplate code when defining classes that mainly store data.

In [ ]:
from dataclasses import dataclass

@dataclass
class Person:
    name: str
    age: int

Person("Bob", 10)

Person(name='Bob', age=10)

# Type Hints
As you have learned by now, the datatypes of variables in python simply depend on what you are assigning to the variable.
However, python is still a strongly typed language and the fact that types are not explicitily denoted in the declaration may lead to confusing code. <br>
To produce code that is more readible and easier to understand we can use __type hints__ (since Python 3.5).  <br> <br>
Using type hints in function declarations we can document the required type of input parameters as well as the type of the function output.

In the example below we expect two inputs of type `float` one parameter of type `bool` and we will output `str`

In [ ]:
def subtract(a: float, b: float, reverse: bool) -> str:
    if reverse:
        res = b - a
    else:
        res = a - b
    return f'Result is: {res}'

Of course we can also use type hints for lists or dictionaries:

In [ ]:
from typing import List, Dict

def addOrExtend(lst: list[str], items: dict[str, List[str]], key: str) -> None:
    if key in items:
        items[key].extend(lst)
    else:
        items[key] = lst

And of course you can also use datatypes from additional libraries such as numpy's `array` or pandas' `DataFrame`.
Sometimes you will also find the more generic `Mapping` or `Sequence` used as parent class of e.g. `dict` or `list`
<br> <br>
We encourage you to use type hints in all of the methods and functions that you are going to define in your homework submissions, as this makes it easier to understand and grade your code. All of the methods that will already be implemented or defined will also include type hints to help you with the exercise.